services:
  - type: web
    name: kk-car-rentals
    runtime: node
    plan: free
    region: singapore # Closest region to India / Asia
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
